### ISSUE TITLE
demo example issue

### ISSUE THREAD

**Issue by Amaryadav7** [NativeScript/nativescript-geolocation#211]
```
Successfully synced application org.nativescript.demoangular on device 04e9b0f47d2a.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
System.err: android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6
System.err: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:225)
System.err: 	at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
System.err: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2160)
System.err: 	at android.content.res.Resources.getAnimation(Resources.java:1181)
System.err: 	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:107)
System.err: 	at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1102)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1600)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
System.err: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
System.err: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
System.err: 	at android.os.Handler.handleCallback(Handler.java:794)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:176)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6656)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
ActivityManager: setHasOverlayUi called on unknown pid: 2523
```

**Comment by tgpetrov** [comment]
@Amaryadav7 can you provide more context to the case where you observe this issue?
I have followed the instructions in the demo-angular's [README](https://github.com/NativeScript/nativescript-geolocation/blob/master/demo-angular/README.md) file and had no issues. 

Also as the app is updated with the latest _tns-android_ and _tns-core-modules_, you can check your nativescript cli version (_tns --version_) and if it is older than 5.3.0, it is a good idea to update it (_npm install -g nativescript_)

**Comment by tgpetrov** [comment]
Closing due to inactivity.
