### ISSUE TITLE
Error on location permissions refused

### ISSUE THREAD

**Issue by TheOnlyMatt** [NativeScript/nativescript-geolocation#94]
### Make sure to check the demo app(s) for sample usage 

App is crashing on my project, there is no problem on another sample project with similar code.

### Which platform(s) does your issue occur on?
- iOS/Android/Both -> Tested only on Android
- iOS/Android versions  -> Android 6.0
- emulator or device. What type of device? Device is Wiko Fever

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): Debug / Release
- Plugin(s): V4.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 

When throwing geolocation permission request, if the users refuses to be located, app crashes with this error : 

```
ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10324 from pid 6563 on display 0
JS: location received
JS: gonna show loader
JS: sending this request : 
JS: https://app-ceairbus.com/wp-json/wp/v2/pages?status=publish&parent=2&per_page=100&orderby=menu_order&order=asc&_embed=true
JS: go ->>> 
JS: sending this request : 
JS: https://app-ceairbus.com/wp-json/custom-api/news
JS: go ->>> 
JS: sending this request : 
JS: https://app-ceairbus.com/wp-json/custom-api/events
System.err: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=3001, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.airbusce.actuce/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onRequestPermissionsResult failed
System.err: TypeError: Calendar._reject is not a function
System.err: File: "file:///data/data/com.airbusce.actuce/files/app/tns_modules/nativescript-calendar/calendar.js, line: 27, column: 17
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/nativescript-calendar/calendar.js', line: 27, column: 18
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err:     Frame: function:'ActivityCallbacksImplementation.onRequestPermissionsResult', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 690, column: 44
System.err:     Frame: function:'NativeScriptActivity.onRequestPermissionsResult', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 38, column: 25
System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3929)
System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3972)
System.err:     at android.app.ActivityThread.-wrap16(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     at android.os.Looper.loop(Looper.java:207)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5728)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onRequestPermissionsResult failed
System.err: TypeError: Calendar._reject is not a function
System.err: File: "file:///data/data/com.airbusce.actuce/files/app/tns_modules/nativescript-calendar/calendar.js, line: 27, column: 17
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/nativescript-calendar/calendar.js', line: 27, column: 18
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err:     Frame: function:'ActivityCallbacksImplementation.onRequestPermissionsResult', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 690, column: 44
System.err:     Frame: function:'NativeScriptActivity.onRequestPermissionsResult', file:'file:///data/data/com.airbusce.actuce/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 38, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onRequestPermissionsResult(NativeScriptActivity.java:61)
System.err:     at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6692)
System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6571)
System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3925)
System.err:     ... 9 more
ActivityManager: Process com.airbusce.actuce (pid 6563) has died
ActivityManager: SVC-handleAppDiedLocked: app = ProcessRecord{7aa4d3e 6563:com.airbusce.actuce/u0a324}, app.pid = 6563
ActivityManager: cleanUpApplicationRecord -- 6563

```

### Is there any code involved? 
Here is my code : 

```
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs/Subject';
var application = require("application");

import * as geolocation from "nativescript-geolocation";

@Injectable()

export class Location {
    onLocationChange: Subject<any> = new Subject<any>();

    private _location : any
    private _located : boolean = false

    constructor(){
        let self = this

        console.log("in constructor")
        geolocation.isEnabled().then(function (enabled) {
            console.log("then")
            if (!enabled) {
                console.log("location not enabled")
                try{
                    geolocation.enableLocationRequest()
                        .then(function () {
                            console.log("after enable location request")
                            self.getUserLocation()
                        }, function (e) {
                            console.log("Error: " + (e.message || e));
                        });
                }
                catch(e){
                    console.log("error enabling location")
                }
                finally{
                    self.location = {
                        latitude : "43.6008028",
                        longitude : "1.3626298"
                    }
                }
            }
            else{
                console.log("location enabled")
                self.getUserLocation()
            }
        }, function (e) {
            console.log("Error: " + (e.message || e));
        });

    }
```

When the app is running, and the user not located, the "location not enabled" log shows.
If the user accept allow the app to locate him, there is no problem, everything is working fine.
Otherwise, if he refuses, the app crashes just after, showing no more log.

Does anybody has an idea why is this happening ?

Thanks in advance for your help !

**Comment by lini** [comment]
The error I see in the logs is not from the nativescript-geolocation plugin but instead seems to involve [nativescript-calendar](https://github.com/eddyverbruggen/nativescript-calendar). More specifically, this line in the code: https://github.com/EddyVerbruggen/nativescript-calendar/blob/fbaa48cbd3dbbfe0dfd78f3e78f489cd5d795e83/calendar.android.js#L29

It seems that the calendar plugin is trying to handle all permission requests, including the one that comes from the geolocation plugin and is failing for some reason. Please open an issue in the calendar repository and mention this bug there.

**Comment by EddyVerbruggen** [comment]
Thanks, @lini, you're right - the Calendar plugin is way too permission-happy. I'll fix that.
